version: "3.8"

services:
  app:
    build: .
    container_name: ssis_app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - ssis

  web:
    image: nginx:alpine
    container_name: ssis_web
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ssis

  db:
    image: mysql:8.0
    container_name: ssis_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DBNAME}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-conf:/etc/mysql/conf.d 
    networks:
      - ssis

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    container_name: ssis_tunnel
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    restart: always
    networks:
      - ssis

volumes:
  db_data:

networks:
  ssis:
